export const REVIEW_FAIL_FIND = 'REVIEW_FAIL_FIND';
export const REVIEW_REQUEST_FIND = 'REVIEW_REQUEST_FIND';
export const REVIEW_SUCCESS_FIND = 'REVIEW_SUCCESS_FIND';

export const REVIEW_FORM = 'REVIEW_FORM';
